services:
  band-on-the-run:
    image: ghcr.io/slmingol/band-on-the-run:latest
    container_name: band-on-the-run
    ports:
      - "3000:80"
    volumes:
      - ./public/audio/stems:/app/public/audio/stems:ro
    restart: unless-stopped
